### ISSUE TITLE
レビュー画面におけるテンプレート欄固定の実装方法の検討

### ISSUE THREAD

**Issue by ltoppyl** [git-baboo/easy-review#110]
## ✨ Summary

- レビュー画面におけるテンプレート欄を、画面スクロール時に、右側に固定する方法についての再検討
- 今回は、スクロールの量に対してテンプレート欄を操作するようにしているが、もっといい方法や、簡潔な方法がありそう
- 機能自体は変更せず、その実装方法について考える

## 🔥 Requirements

- 機能自体の変更はなし

## ✅ Tasks

- [ ] xxx

**Comment by watagit** [comment]
JavaScript 的アプローチから CSS 的アプローチに実装方法を変更すれば解消できそう

### 参考文献
https://tech-dig.jp/css%E3%81%A0%E3%81%91%E3%81%A7%E3%82%B5%E3%82%A4%E3%83%89%E3%83%90%E3%83%BC%E3%82%92%E5%9B%BA%E5%AE%9A%E3%83%BB%E3%82%B9%E3%82%AF%E3%83%AD%E3%83%BC%E3%83%AB%E3%81%AB%E8%BF%BD%E5%BE%93%E3%81%99/
