### ISSUE TITLE
トップ画面にPR が表示される時とそうでない時がある

### ISSUE THREAD

**Issue by ltoppyl** [git-baboo/easy-review#112]
## 🐛 Summary

- トップ画面で、PRが表示されるときとそうでない時がある

## 📸 Screenshot

ふたつの画像の前後でGitHubは特に操作されていないため、自分がレビュワーのPR に変更はない。
![image](https://user-images.githubusercontent.com/68209431/138674669-c3892cd8-a179-4253-a65f-9a4d5b4147e3.png)
![image](https://user-images.githubusercontent.com/68209431/138674626-88946d16-014d-4cb8-a2d1-016c8b407d52.png)

## 👀 Steps

1. `localhost:3000` にアクセスする
2. 自分がレビュワーのPR が表示されない

## 🎨 Expected Behavior

- トップ画面に常に自分がレビュワーのPR が正しく表示される

## 📦️ Environment

- Windows 
- Chrome / Edge

## ✅ Tasks

- [ ] xxx

**Comment by watagit** [comment]
完全に理解した
