### ISSUE TITLE
レビュー画面でコメントを追加せずに完了ボタンを押すとエラーが出る

### ISSUE THREAD

**Issue by ltoppyl** [git-baboo/easy-review#114]
## 🐛 概要

- レビュー画面で何もレビューを記載せずに完了ボタンが押された時に、エラー画面が表示される
- 完了ボタンが押された後、コメント完了に伴うToast や、トップ画面への遷移が行われてしまう

## 📸 スクリーンショット

⇓ 何もレビューを書かずに完了ボタンを押したら表示されるエラー
![image](https://user-images.githubusercontent.com/68209431/138675720-5afa04d7-c6d7-47fe-a469-26b52a2b4c62.png)

## 👀 再現手順

1. レビュー画面でなにもレビューを書かずに完了ボタンを押す
2. レビューが完了した旨のToast が表示され、トップ画面に移動
3. 数秒後に、スクリーンショットと同様の画面が表示される

## 📦️ バグを確認した環境

- Windows 
- Chrome / Edge

## 💡 解決策

コメントがひとつも追加されていない状態で完了ボタンが押されると、コメントがひとつもない旨のメッセージが Toast で表示される

**Comment by watagit** [comment]
@mikiya1130 
Toast に表示するメッセージ決めたので Figma 見ながら実装お願いします〜！

![image](https://user-images.githubusercontent.com/44804976/144704031-a294efc9-dbdb-4a3e-8ede-93cbdff68ef9.png)

**Comment by watagit** [comment]
@mikiya1130 このイシューとか私やれそうだけど、どうだろう？他のイシュー重そうだったら私に渡してもらって OK よ！ 👌

**Comment by mikiya1130** [comment]
@watagit 
進捗に関して音沙汰なくてごめん
現在 #116 の解消と合わせて、review ページで追加したコメントの管理とか、バグの修正(原因は分かってる)とか考えてます
どうしたらいいかはほぼ分かってて、ただ react-diff-view 拡張機能の理解、useReducer の理解、この2つがちょっと追いついてなくて実際どう書けそうか調べてる感じです

この Issue に関しては、負担は大きくないけど、せっかく声かけてくれてるし余裕あるならお願いします
コメントの有無の判定で詰まったらトーストの実装だけしてパスしてもらっても大丈夫です

**Comment by watagit** [comment]
了解！
