### ISSUE TITLE
差分表示において、バイナリファイルの場合、その旨を表示する

### ISSUE THREAD

**Issue by mikiya1130** [git-baboo/easy-review#120]
## ✨ Summary

差分表示において、バイナリファイルの場合、その旨を表示する
現在は、空のファイルのヘッダ部分が表示されている状態
本家に合わせ、当該ファイル名とバイナリファイルの差分は表示できない旨の表示を追加する

## 📷 Screenshot

参考：#92

### 本家
![Screenshot-20211025210753-918x191](https://user-images.githubusercontent.com/63896499/138692229-d8abbb24-dda3-4327-8cd6-8f7ab92e5e43.png)

### Easy Review
![Screenshot-20211025210817-720x99](https://user-images.githubusercontent.com/63896499/138692285-05d582b9-9613-4ca0-8307-9f44267d69fd.png)

## 関連 Issue
- #117 
- #118 
- #119 

### 表示されるメッセージに関して
とりあえずそれっぽいの書いてみたけど、提案あればぜひお願いします

### レビューしたいけど、バイナリファイルの差分を含むプルリクどれやねん
( ´･ω･)⊃ #172 
```
/git-baboo/easy-review/172/review
```

**Comment by watagit** [comment]
- ライブラリ側にバグがある
- ライブラリ側で既に PR 提出済み
- ライブラリが1年ほど更新されていないため、PR がレビューされないかも

**Comment by watagit** [comment]
方向性としては、ライブラリ側の反応を待つ間に easy-review 内で独自実装していく
