### ISSUE TITLE
DiffFiles の命名変更

### ISSUE THREAD

**Issue by watagit** [git-baboo/easy-review#137]
## ✨ Summary

**1意見としてのイシュー**
個人的には`map`を使用して何かしらを展開する系のコンポーネントは`~List`の命名の方がしっくりくると感じているため、命名を変更したい
こんな記事もあるので読んでみてほしい

[[Qiita] リスト系のコンポーネント名 Images と ImageList はどっちが有利か](https://qiita.com/misuken/items/d62c304fd6d730801ddb)

## 🔥 Requirements

- `DiffFiles`の命名について議論されること
- `DiffFiles`の命名が決まること
  - 必要であれば命名が変更されること

**Comment by watagit** [comment]
@git-baboo/dev-team これ意見ほしい！

**Comment by mikiya1130** [comment]
@watagit 
List でも良いと思います
`PullRequestList` とか `TemplateList` と揃える意味でも
変更する場合、ファイル内で定義してる[変数 `files`](https://github.com/git-baboo/easy-review/blob/08360cbbde6fb290fc459b1949f2990863a27c84/src/components/review/DiffFiles.tsx?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L14) の命名も合わせて修正？(を Issue に含めませんか？)

**Comment by ltoppyl** [comment]
ぼくも List でいいのではないかと思います。
英弱なので、複数形使ってると、複数形のスペルちげーよって煽られる未来しか見えません…

**Comment by watagit** [comment]
ok!
このイシューは私やっちゃいます！
