### ISSUE TITLE
ReviewTitle の設計変更

### ISSUE THREAD

**Issue by watagit** [git-baboo/easy-review#139]
## ✨ Summary

`ReviewTitle.tsx`の設計を変更したい。

#### 命名
現在の`ReviewTitle`が表している部分は「プルリクエストのオーナー名とリポジトリの名前」と「プルリクエストのタイトル」である。コンポーネント名と実際に表現している役割が異なるので、より意味のある命名にしたい。

#### 設計
「プルリクエストのオーナー名とリポジトリの名前」と「プルリクエストのタイトル」で分けて考えるのではなく「プルリクエストのオーナー名とリポジトリの名前」と「プルリクエストのタイトル」を1つのコンポーネントにまとめた方がきれいになりそう

## 🔥 Requirements

- ReviewTitle の部分が適切に設計されること

## 📄 References

https://github.com/git-baboo/easy-review/blob/940d7f27be98724ee791ff5c4c6355734f801503/src/pages/review.tsx#L133-L134

**Comment by ltoppyl** [comment]
@watagit 
【質問？相談？】

> 「プルリクエストのオーナー名とリポジトリの名前」と「プルリクエストのタイトル」で分けて考えるのではなく「プルリクエストのオーナー名とリポジトリの名前」と「プルリクエストのタイトル」を1つのコンポーネントにまとめた方がきれいになりそう

⇨  下の画像の赤枠の部分を1つのコンポーネントにしたら！？っていう話だと思うんだけど、
　  赤枠部分をひとまとめにするんだったら、いっそのこと青枠の部分でひとまとめにしたらどうだろう！？
　  と思った次第です。
      https://github.com/git-baboo/easy-review/blob/940d7f27be98724ee791ff5c4c6355734f801503/src/pages/review.tsx#L133-L138


![image](https://user-images.githubusercontent.com/68209431/140844706-a69b5acf-3e67-4eaa-a35a-bcfaec9d7ee4.png)

**Comment by watagit** [comment]
@ltoppyl その設計で良いと思う！
