### ISSUE TITLE
Detail ページと Review ページのプルリク情報部分を共通化する

### ISSUE THREAD

**Issue by mikiya1130** [git-baboo/easy-review#150]
## ✨ Summary

https://github.com/git-baboo/easy-review/blob/eddd7a84d74a274567f20b04406754aa8ad1f032/src/pages/detail.tsx#L54-L58
https://github.com/git-baboo/easy-review/blob/eddd7a84d74a274567f20b04406754aa8ad1f032/src/components/review/PullRequestHeading.tsx#L15-L23
を共通化する

- Detail ページと Review ページのプルリク情報部分が同一コンポーネントを共有するようにする
- 使用しているコンポーネントや指定しているプロパティに差異があるが、基本的に Figma に従う

## 📸 該当箇所
![image](https://user-images.githubusercontent.com/68209431/140879019-ae211e76-2463-4959-bdc4-806a91ec4721.png)

**Comment by ltoppyl** [comment]
@watagit 
@mikiya1130 
' easy-review/src/pages/detail.tsx '

**Comment by mikiya1130** [comment]
@ltoppyl 
上のリンククリックしたら、当時のコミットの `detail.tsx` ファイルの該当箇所に飛べると思うよ
一応再掲↓
https://github.com/git-baboo/easy-review/blob/eddd7a84d74a274567f20b04406754aa8ad1f032/src/pages/detail.tsx#L54-L58
URL 見たら、コミットハッシュとか含まれてることが分かると思う
(ブランチ切り替えるプルダウンの表示も同様にコミットハッシュになってるはず)

---

じゃなくて、その箇所が現在どのファイルのどこにいってるかって話か
next 移行前の `src/pages/detail.tsx` は、移行後は `src/pages/[owner]/[repo]/[pullNumber]/index.tsx` やな
(`git mv` 使ってない？のか分からんけど履歴は途切れてるから、仮に初見やと対応ファイルは自力で頑張って見つける必要がある)
その後該当箇所の変更履歴はなく、↓にそのまま残ってるな
https://github.com/git-baboo/easy-review/blob/f47be5b3cafecb01bc1eab3e1ac313443f980165/src/pages/%5Bowner%5D/%5Brepo%5D/%5BpullNumber%5D/index.tsx#L53-L57

**Comment by ltoppyl** [comment]
ありがとーーー！
