### ISSUE TITLE
絵文字にカラーが無くなっている

### ISSUE THREAD

**Issue by ltoppyl** [git-baboo/easy-review#164]
## 🐛 Summary

- ページ中に使われている顔文字が、白黒になっている

## 📸 Screenshot

<img src="https://user-images.githubusercontent.com/68209431/144698545-410822bf-3f50-4d0b-889a-a4b5b6a7482a.png" width=50%>
<img src="https://user-images.githubusercontent.com/68209431/144698491-bbe69714-cab0-4b81-b143-e6bb1d0c43b1.png" width=30%>

## 🎨 Expected Behavior

- 顔文字が、カラーで表示される

## 📦️ Environment

- Windows
- Chrome / Edge

## ✅ Tasks

- [ ] xxx

**Comment by watagit** [comment]
11/20 の記事
これ関わってそう

[【Chrome】絵文字に色が付かない・絵文字が白黒になる不具合について](https://did2memo.net/2021/11/20/chrome-update-emoji-color-issue)

**Comment by watagit** [comment]
Windows 版 Chrome の問題だったのでクローズしちゃいます
