### ISSUE TITLE
ページのアイコンが△マークになっている

### ISSUE THREAD

**Issue by ltoppyl** [git-baboo/easy-review#165]
## 📸 Screenshot

<img src="https://user-images.githubusercontent.com/68209431/144698682-1876980e-60c7-4fdf-ae5a-c9833f84bdac.png" width=100%>
<img src="https://user-images.githubusercontent.com/68209431/144698638-46b067d6-49d2-4c53-9543-e73479c5d76a.png" width=30%>

## 🎨 Expected Behavior

- アイコンとして、適切なものが表示されるようになる

## 📦️ Environment

- Windows
- Chrome / Edge

**Comment by watagit** [comment]
Next.js へ移行する際に favicon の設定を完全に忘れてたせいだぁぁぁ！
これは私がやりまっす
