### ISSUE TITLE
レビューコメント追加時の、レビュー者のアイコン＆名前を、ダミーから変更する

### ISSUE THREAD

**Issue by ltoppyl** [git-baboo/easy-review#174]
## ✨ Summary

- 現状、レビューコメント追加時のアイコン＆名前がダミーデータになっている
- このダミーデータを適切なものに変更する

## 🔥 Requirements

- レビューを投稿する際の、レビュー者のアイコン＆名前が適切なものになっている
- 不要になったダミーデータ  `src/data/dummyReviewer.ts`  を削除する

## 📷 Screenshot

![image](https://user-images.githubusercontent.com/68209431/145703448-4dedce15-17a5-40d6-a9b5-bb066e636a67.png)

## 🌏 方針

以下の流れで実装していけばできそう！

1. レビュー者のアイコンと名前がどこで指定されているか確認する
今回は`src/pages/[owner]/[repo]/[pullNumber]/review.tsx`内で useWidget に対して情報を渡すことで指定しています
https://github.com/git-baboo/easy-review/blob/d4a88052519b6a2782957ce1f6ebb4efc60bb945/src/pages/%5Bowner%5D/%5Brepo%5D/%5BpullNumber%5D/review.tsx#L43
reviewer はユーザ名とアイコンのパス（画像そのものでなく URL）からなるオブジェクトです

1のtodo
- [x] レビュー者のアイコンと名前がどこで指定されているか確認する（useWidget を理解する必要はない）
- [x] `src/data/dummyReviewer.ts`の値を変えてみて、コメントに表示される値が変わることを確認する

2. ログイン中ユーザの情報をコンソールに表示してみる
使用しているダミーの情報をログイン中（つまり自分）のユーザ名とアイコンを取得する必要があります。ここでいざ API 通信の実践！はじめに自分の情報を取得するエンドポイントを叩いてみましょう。今回使うべきエンドポイントは[これ](https://docs.github.com/ja/rest/reference/users#get-the-authenticated-user)です
API から取得した情報の保存場所等はあまり考えず、`src/pages/[owner]/[repo]/[pullNumber]/review.tsx`内の useEffect 内でコンソールに表示するところからはじめてみると良さそうです（既に useEffect が1つ作られてるので、既存の useEffect の後ろに新たに useEffect を宣言したほうが良さそう。**useEffect の第二引数に`[]`をつけることを忘れずに**）

2のtodo
- [x] 既存の useEffect の後ろに新たに useEffect を宣言する
- [x] 新たに宣言した useEffect 内で該当するエンドポイントを叩いて返ってきた値をコンソールに表示する（このとき octokit を使う。fetch で試してみても良い）

3. useState に API から取得したユーザ名とアイコンの URL を保存する
コンソールに API から取得したデータが表示できたら、その値を保存しましょう
今回は useState に情報を持つだけで十分だと思うので、この方針で行きましょう（ログイン中のユーザ情報を他の場所でも使い回す必要が出てきたらグローバルに持つべき）
useState を宣言する際の型は自分で定義した方が良さそうです。既に`src/types/CurrentUserType.ts`にそれっぽい型が宣言されていますが、今回は`src/pages/[owner]/[repo]/[pullNumber]/review.tsx`内に独自で宣言して良いと思います。
最終的には、2 で宣言した useEffect の中で set~ するイメージです

3のtodo
- [x] ユーザ名とアイコン URL を管理するために useState を宣言する（型を独自で宣言する）
- [x] useEffect 内で API から取得した値を set~ で保存する

4. useState で持っている情報を useWidget に渡す
ここまでくればもう終わりといっても過言ではないです
useWidget に渡しているダミーデータを useState で管理しているデータに置き換えましょう

4のtodo
- [x] useWidget に渡しているダミーデータを useState で管理しているデータに置き換える

5. 動作確認
実際にコメントを追加してみて、自分のユーザ名とアイコンが表示されているか確認しましょう

5のtodo
- [x] 実際のコメントに自分のユーザ名とアイコンが表示されることを確認する

**Comment by watagit** [comment]
@ltoppyl 
実装方針を追記したので、確認の上実装始めちゃって ok です！
詰まったり不明な点あったら随時メンション飛ばしてくだされ〜

**Comment by ltoppyl** [comment]
> @ltoppyl 
> 
> 実装方針を追記したので、確認の上実装始めちゃって ok です！
> 
> 詰まったり不明な点あったら随時メンション飛ばしてくだされ〜

ありがとうございますー！
