### ISSUE TITLE
レビューコメント投稿フォームでフォーカスが外れる

### ISSUE THREAD

**Issue by watagit** [git-baboo/easy-review#219]
## 🐛 概要

レビューコメントを投稿するフォームで1文字打ち込むごとにフォーカスが外れてしまう。

## 📸 スクリーンショット

[![Image from Gyazo](https://i.gyazo.com/9b872f57611b4993c6661dc91310d7b1.gif)](https://gyazo.com/9b872f57611b4993c6661dc91310d7b1)

## 👀 再現手順

1. 任意のレビュー画面にアクセスする
2. ＋ボタンからレビューコメント投稿フォームを展開する
3. 文字を打ち込む
4. 1文字打ち込むごとにフォーカスが外れる

## 🎨 期待する挙動

フォーカスが外れずに円滑に入力ができる

## 📦️ 環境

- macOS
- Chrome / Safari / Firefox

## 💡 解決策

コンポーネントが分割されておらず、過剰な再生成が行われている可能性がある

## ✅ タスク

- [x] 原因の究明
- [x] 解消

**Comment by watagit** [comment]
#187 のプレビュー環境では正常に入力できるが、 #189 のプレビュー環境では同様のバグが起きている

**Comment by watagit** [comment]
これが原因ぽい
[Qiita - [React]フォーム入力の度にフォーカスが外れてしまうときに確認すべきこと2選](https://qiita.com/iron-samurai/items/5d88e255f18280d6941d#%E5%8E%9F%E5%9B%A0)

**Comment by mikiya1130** [comment]
#187 から #189 の間で、厳密には #181 を取り込んだタイミングやな
更に具体的には、`renderDiff` 関数を `RenderDiff` コンポーネントにしたとき (d00d15632184d8facb27f8a30ba64c9f8f3dfbbc → 599f834f44752192078e4c622baf7091c8badbf4)
https://github.com/git-baboo/easy-review/pull/181/commits
