### ISSUE TITLE
[レビュー画面] 完了ボタンを上に配置する

### ISSUE THREAD

**Issue by watagit** [git-baboo/easy-review#224]
## ✨ 概要

現状、DiffFileList の下に完了ボタンが配置されている。差分が大きい PR だと下までスクロールしないと完了ボタンが押せない。
これはユーザにとって煩わしいので、GitHub 本家と同じように完了ボタンを上に配置する

## 🔥 ゴール

- [ ] Figma で完了ボタン周りのデザインが修正される
- [ ] コード上で完了ボタンの配置が修正される

**Comment by mikiya1130** [comment]
思いついたこと
- 右下（TemplateList の下）の空間が空いているので、そこに配置して活用する
- スクロールしなくても下固定しておく

これら（と提案してくれてる上側も含め）配置によらず、それに掛け合わせて、
- 1つ以上のレビューを書いたらボタン出現

もありかもしれない

**Comment by watagit** [comment]
@mikiya1130 
個人的には PullRequestHeading の右側がちょうど空いてるな〜と思ってて
こんな感じで本家リスペクトな感じでもいいのかなと

![image](https://user-images.githubusercontent.com/44804976/153199984-540a22dd-4234-4316-92a9-729002b9dd09.png)

スクロールしたら PullRequestHeading と一緒に追従していくみたいな

![image](https://user-images.githubusercontent.com/44804976/153200080-98d0139d-0009-4bb0-83c3-1837af4091a0.png)

[Figma](https://www.figma.com/file/dZqHYteyuTFcrklNVMjNui/easy-review?node-id=1410%3A10002)
