### ISSUE TITLE
1行あたりの文字数を増やす

### ISSUE THREAD

**Issue by watagit** [git-baboo/easy-review#241]
## ✨ 概要

レビュー画面で表示されるソースコードの1行あたりの文字数が少なく見づらいため、改善する。
フォントサイズを小さくするなどして対応する

## 🔥 ゴール

- [ ] ソースコードが見やすくなる

## 📄 参考資料

- [テストユーザからの要望](https://discord.com/channels/931439340263977041/931441677892223057/940500473843179540)

**Comment by ltoppyl** [comment]
@watagit   @mikiya1130 
文字サイズの変更って、 ⇓⇓⇓ らへん
https://github.com/git-baboo/easy-review/blob/develop/src/components/review/DiffRenderer.tsx#L75~L81
を、なんやかんやすればできるのかなーと思って "react-diff-view" の レポジトリー (https://github.com/otakustay/react-diff-view) とか見てみたけど、なんかよくわからなくて、手詰まり中です
助けてくださいm(_ _)m

**Comment by watagit** [comment]
@ltoppyl 
まだ全部見れてるわけではないけど、ここが参考になりそう
https://github.com/otakustay/react-diff-view#css-variables

うちだと、src/style/difffile.css で諸々のスタイルを管理してるって感じかな

@mikiya1130 の方が詳しいと思うから何かサポートできそうであればコメントお願いシャス！

**Comment by ltoppyl** [comment]
@watagit   @mikiya1130 
文字サイズの変更できましたーm(_ _)m
