### ISSUE TITLE
詳細画面のマークダウン部分でコメントアウトが表示される

### ISSUE THREAD

**Issue by watagit** [git-baboo/easy-review#32]
## 🐛 Summary

詳細画面のマークダウン形式で表示する部分でコメントアウトも一緒に表示されてしまっている。

## 📸 Screenshot

![スクリーンショット 2021-10-21 9 25 54](https://user-images.githubusercontent.com/44804976/138190208-09b171ad-5ee5-48d6-994f-8b35768d6d3b.png)

## 👀 Steps

1. 詳細画面にアクセスする
2. コメントアウトが表示されている

## 🎨 Expected Behavior

コメントアウトの部分が表示されない

## 📦️ Environment

- macOS
- Chrome / Safari / Firefox / Edge

## 💡 Solution

何かしらのオプションで変更できそうな気がしてるが、少し調べた感じだと別途プラグイン的なのが必要そう？

- https://github.com/remarkjs/react-markdown/issues/558

## ✅ Tasks

- [ ] xxx

**Comment by watagit** [comment]
@mikiya1130 これ何か知ってたりする？？

**Comment by mikiya1130** [comment]
@watagit 
ホントや！全然気にしてなかった
markdown を入力として変換してるので、そうなるのはある意味正しい挙動ではある
おそらく HTML タグ書くと、全てそのまま表示される予感
Solution にも書いてくれてるけど、オプションなど調査してみます
